# Generated by Django 4.1 on 2022-11-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='dateCreated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
