name: Secrets

on: push

jobs:
  test_env:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Supersecretscript
      run: python -c 'import os;print(os.environ)'
      env:
        M_API_KEY: ${{ secrets.M_API_KEY }}


  
